package com.example.faculty.entity;

public enum AuditAction {
    LOGIN,
    LOGOUT,
<<<<<<< HEAD
=======
    REGISTER,
>>>>>>> b100b436eab738f8f9eca6812bdd01701ec097b3
    CREATE_PROFILE,
    UPDATE_PROFILE,
    ADD_EDUCATION,
    UPDATE_EDUCATION,
    DELETE_EDUCATION,
    ADD_EXPERIENCE,
    UPDATE_EXPERIENCE,
    DELETE_EXPERIENCE,
    UPLOAD_DOCUMENT,
    UPDATE_DOCUMENT,
    DELETE_DOCUMENT,
    APPROVE_DOCUMENT,
    REJECT_DOCUMENT,
    DOWNLOAD_DOCUMENT,
    PREVIEW_DOCUMENT,
    REUPLOAD_DOCUMENT
}
